const products = [
	{
	  imageSrc: './images/blackTShort.png',
	  title: 'Товар',
	  date: '17.09.2023',
	  type: 'clothes',
	},
	{
	  imageSrc: './images/grayTShort.png',
	  title: 'Товар',
	  date: '19.09.2023',
	  type: 'clothes',
	},
	{
	  imageSrc: './images/blackTShort.png',
	  title: 'Товар',
	  date: '22.09.2023',
	  type: 'clothes',
	},
	{
	  imageSrc: './images/whiteTShort.png',
	  title: 'Товар',
	  date: '15.09.2023',
	  type: 'clothes',
	},
	{
	  imageSrc: './images/grayTShort.png',
	  title: 'Товар',
	  date: '28.09.2023',
	  type: 'clothes',
	},
	{
	  imageSrc: './images/blackTShort.png',
	  title: 'Товар',
	  date: '11.09.2023',
	  type: 'clothes',
	},
	{
	  imageSrc: './images/grayTShort.png',
	  title: 'Товар',
	  date: '05.09.2023',
	  type: 'clothes',
	},
	{
	  imageSrc: './images/blackTShort.png',
	  title: 'Товар',
	  date: '20.09.2023',
	  type: 'clothes',
	},
	{
	  imageSrc: './images/whiteTShort.png',
	  title: 'Товар',
	  date: '24.09.2023',
	  type: 'clothes',
	},
	{
	  imageSrc: './images/grayTShort.png',
	  title: 'Товар',
	  date: '09.09.2023',
	  type: 'clothes',
	},
	{
	  imageSrc: './images/blackTShort.png',
	  title: 'Товар',
	  date: '13.09.2023',
	  type: 'clothes',
	},
	{
	  imageSrc: './images/grayTShort.png',
	  title: 'Товар',
	  date: '01.09.2023',
	  type: 'clothes',
	},
	{
	  imageSrc: './images/blackTShort.png',
	  title: 'Товар',
	  date: '06.09.2023',
	  type: 'clothes',
	},
	{
	  imageSrc: './images/whiteTShort.png',
	  title: 'Товар',
	  date: '08.09.2023',
	  type: 'clothes',
	},
	{
	  imageSrc: './images/grayTShort.png',
	  title: 'Товар',
	  date: '27.09.2023',
	  type: 'clothes',
	},
	{
	  imageSrc: './images/shoes_1.png',
	  title: 'Nuke',
	  date: '16.09.2023',
	  type: 'shoes',
	},
	{
	  imageSrc: './images/shoes_2.png',
	  title: 'Abibass',
	  date: '23.09.2023',
	  type: 'shoes',
	},
	{
	  imageSrc: './images/shoes_4.png',
	  title: 'Nuke Jordamn',
	  date: '10.09.2023',
	  type: 'shoes',
	},
	{
	  imageSrc: './images/shoes_1.png',
	  title: 'Nuke',
	  date: '26.09.2023',
	  type: 'shoes',
	},
	{
	  imageSrc: './images/shoes_3.png',
	  title: 'Рита',
	  date: '18.09.2023',
	  type: 'shoes',
	},
	{
	  imageSrc: './images/shoes_4.png',
	  title: 'Nuke Jordamn',
	  date: '07.09.2023',
	  type: 'shoes',
	},
	{
	  imageSrc: './images/shoes_2.png',
	  title: 'Abibass',
	  date: '14.09.2023',
	  type: 'shoes',
	},
	{
	  imageSrc: './images/shoes_1.png',
	  title: 'Nuke',
	  date: '21.09.2023',
	  type: 'shoes',
	},
	{
	  imageSrc: './images/shoes_2.png',
	  title: 'Abibass',
	  date: '02.09.2023',
	  type: 'shoes',
	},
	{
	  imageSrc: './images/shoes_4.png',
	  title: 'Nuke Jordamn',
	  date: '12.09.2023',
	  type: 'shoes',
	},
	{
	  imageSrc: './images/shoes_1.png',
	  title: 'Nuke',
	  date: '04.09.2023',
	  type: 'shoes',
	},
	{
	  imageSrc: './images/shoes_3.png',
	  title: 'Рита',
	  date: '25.09.2023',
	  type: 'shoes',
	},
	{
	  imageSrc: './images/shoes_4.png',
	  title: 'Nuke Jordamn',
	  date: '03.09.2023',
	  type: 'shoes',
	},
	{
	  imageSrc: './images/shoes_2.png',
	  title: 'Abibass',
	  date: '29.09.2023',
	  type: 'shoes',
	},
	{
	  imageSrc: './images/shoes_1.png',
	  title: 'Nuke',
	  date: '22.09.2023',
	  type: 'shoes',
	},
	{
	  imageSrc: './images/shoes_2.png',
	  title: 'Abibass',
	  date: '05.09.2023',
	  type: 'shoes',
	},
	{
	  imageSrc: './images/shoes_4.png',
	  title: 'Nuke Jordamn',
	  date: '17.09.2023',
	  type: 'shoes',
	},
	{
	  imageSrc: './images/shoes_1.png',
	  title: 'Nuke',
	  date: '28.09.2023',
	  type: 'shoes',
	},
	{
	  imageSrc: './images/shoes_3.png',
	  title: 'Рита',
	  date: '09.09.2023',
	  type: 'shoes',
	},
	{
	  imageSrc: './images/shoes_4.png',
	  title: 'Nuke Jordamn',
	  date: '20.09.2023',
	  type: 'shoes',
	},
	{
	  imageSrc: './images/shoes_2.png',
	  title: 'Abibass',
	  date: '01.09.2023',
	  type: 'shoes',
	},
	{
	  imageSrc: './images/access_1.png',
	  title: 'Nuke',
	  date: '13.09.2023',
	  type: 'access',
	},
	{
	  imageSrc: './images/access_4.png',
	  title: 'Nuke',
	  date: '15.09.2023',
	  type: 'access',
	},
	{
	  imageSrc: './images/access_2.png',
	  title: 'Nuke',
	  date: '11.09.2023',
	  type: 'access',
	},
	{
	  imageSrc: './images/access_3.png',
	  title: 'Nuke',
	  date: '19.09.2023',
	  type: 'access',
	},
	{
	  imageSrc: './images/access_4.png',
	  title: 'Nuke',
	  date: '06.09.2023',
	  type: 'access',
	},
	{
	  imageSrc: './images/access_5.png',
	  title: 'Nuke',
	  date: '27.09.2023',
	  type: 'access',
	},
	{
	  imageSrc: './images/access_2.png',
	  title: 'Nuke',
	  date: '23.09.2023',
	  type: 'access',
	},
	{
	  imageSrc: './images/access_1.png',
	  title: 'Nuke',
	  date: '08.09.2023',
	  type: 'access',
	},
	{
	  imageSrc: './images/access_4.png',
	  title: 'Nuke',
	  date: '16.09.2023',
	  type: 'access',
	},
	{
	  imageSrc: './images/access_2.png',
	  title: 'Nuke',
	  date: '24.09.2023',
	  type: 'access',
	},
	{
	  imageSrc: './images/access_3.png',
	  title: 'Nuke',
	  date: '10.09.2023',
	  type: 'access',
	},
	{
	  imageSrc: './images/access_4.png',
	  title: 'Nuke',
	  date: '07.09.2023',
	  type: 'access',
	},
	{
	  imageSrc: './images/access_5.png',
	  title: 'Nuke',
	  date: '04.09.2023',
	  type: 'access',
	},
	{
	  imageSrc: './images/access_2.png',
	  title: 'Nuke',
	  date: '14.09.2023',
	  type: 'access',
	},
	{
	  imageSrc: './images/access_1.png',
	  title: 'Nuke',
	  date: '30.09.2023',
	  type: 'access',
	},
	{
	  imageSrc: './images/access_4.png',
	  title: 'Nuke',
	  date: '26.09.2023',
	  type: 'access',
	},
	{
	  imageSrc: './images/access_2.png',
	  title: 'Nuke',
	  date: '06.09.2023',
	  type: 'access',
	},
	{
	  imageSrc: './images/access_3.png',
	  title: 'Nuke',
	  date: '12.09.2023',
	  type: 'access',
	},
	{
	  imageSrc: './images/access_4.png',
	  title: 'Nuke',
	  date: '17.09.2023',
	  type: 'access',
	},
	{
	  imageSrc: './images/access_5.png',
	  title: 'Nuke',
	  date: '29.09.2023',
	  type: 'access',
	},
	{
	  imageSrc: './images/access_2.png',
	  title: 'Nuke',
	  date: '05.09.2023',
	  type: 'access',
	},
	{
	  imageSrc: './images/access_1.png',
	  title: 'Nuke',
	  date: '21.09.2023',
	  type: 'access',
	},
	{
	  imageSrc: './images/access_4.png',
	  title: 'Nuke',
	  date: '28.09.2023',
	  type: 'access',
	},
	{
	  imageSrc: './images/access_2.png',
	  title: 'Nuke',
	  date: '03.09.2023',
	  type: 'access',
	},
  ];
  
export default products